### ISSUE TITLE
Something weird happened and NPC failed to build

### ISSUE THREAD

**Issue by BrendaCayzac** [elizeuangelo/fvtt-module-npc-generator-dnd5e-faq#2]
Hi, I saw on itch.io that you were looking into this, but I wanted to open an issue here.
Trying to generate any NPC will result in an error: "Something weird happened and NPC failed to build"

![image](https://github.com/user-attachments/assets/c087fed6-3939-4753-9eac-b8dda5c94dbd)

Is there any update on a fix for this? I'm running v.12 Build 331.

**Comment by elizeuangelo** [comment]
Sorry about the delays, it took a lot of work but it should be properly working now with the latest dnd version. Please let me know if you find any issues.
